In [25]:
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression

In [79]:
img = cv2.imread(os.getcwd() + '\\..\\final.jpg')
height, width, __ 	= img.shape
n = 3

In [81]:
means = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [91]:
for i in range(n-1):
	for j in np.arange(i,n-1):
		if i == 0 and j == 0:
			regions_diffs = np.array([means[i]-means[j+1]]) 
		else:
			regions_diffs = np.append(regions_diffs, [means[i]-means[j+1]], axis=0)

[-6 -6 -6]
[[-3 -3 -3]]
[-3 -3 -3]
[[-3 -3 -3]
 [-6 -6 -6]]


In [92]:
regions_diffs

array([[-3, -3, -3],
       [-6, -6, -6],
       [-3, -3, -3]])

In [96]:
channels_RGB = ['R', 'G', 'B']
channels_HSV = ['H', 'S', 'V']
channels_Lab = ['L', 'a', 'b']
names = []

for i in range(n-1):
	for j in range(i, n-1):
		for channel in channels_RGB:
			names.append(str(i) + '_' + str(j+1) + '_' + channel + '_diff')

In [111]:
names_R = [1, 2, 3]
names_H = [0, 0, 0]
names_L = [100,100,100]

In [113]:
names = [names_R, names_H]
names = [item for sublist in names for item in sublist]

In [114]:
names

[1, 2, 3, 0, 0, 0]

In [116]:
names = [names, names_L]
names = [item for sublist in names for item in sublist]

In [117]:
names

[1, 2, 3, 0, 0, 0, 100, 100, 100]